import { EstateDealType } from '../models/estate-deal-type.enum';

export const estateDealsMock = [
  {
    id: 9,
    price: 3510.7,
    noi: 126.32,
    capRate: 0.87,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.LEASE,
    name: 'Hampton Anthony',
    dealName: 'Bellfountain',
    address: '814 Graham Avenue, Newkirk, New Hampshire, 3221',
  },
  {
    id: 0,
    price: 1262.36,
    noi: 305.23,
    capRate: 0.29,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.DEVELOPMENT,
    name: 'Araceli Whitney',
    dealName: 'Hartsville/Hartley',
    address: '726 Nevins Street, Makena, West Virginia, 8677',
  },
  {
    id: 2,
    price: 1906.06,
    noi: 228.47,
    capRate: 0.71,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.AQUISITION,
    name: 'Silvia Mcgee',
    dealName: 'Geyserville',
    address: '358 Barwell Terrace, Klondike, Iowa, 2961',
  },
  {
    id: 13,
    price: 1685.88,
    noi: 250.03,
    capRate: 0.68,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.DEVELOPMENT,
    name: 'Suarez Kramer',
    dealName: 'Bluetown',
    address: '620 Newkirk Placez, Loyalhanna, Marshall Islands, 5407',
  },
  {
    id: 7,
    price: 1384.85,
    noi: 309.82,
    capRate: 0.04,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.LEASE,
    name: 'Wilda Morrison',
    dealName: 'Celeryville',
    address: '685 Sedgwick Street, Vienna, Rhode Island, 4638',
  },
  {
    id: 62,
    price: 3911.02,
    noi: 378.63,
    capRate: 0.24,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.LEASE,
    name: 'Anderson Briggs',
    dealName: 'Gratton',
    address:
      '653 Euclid Avenue, Ventress, Federated States Of Micronesia, 6758',
  },
  {
    id: 41,
    price: 3930.4,
    noi: 229.96,
    capRate: 0.81,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.AQUISITION,
    name: 'Maynard Reese',
    dealName: 'Rossmore',
    address: '344 Menahan Street, Yukon, Maryland, 6050',
  },
  {
    id: 65,
    price: 2225.33,
    noi: 296.99,
    capRate: 0.1,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.LEASE,
    name: 'Clarice Bray',
    dealName: 'Veyo',
    address: '365 Everit Street, Marion, Tennessee, 4670',
  },
  {
    id: 5,
    price: 1588.13,
    noi: 366.19,
    capRate: 0.53,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.DEVELOPMENT,
    name: 'Peck Powell',
    dealName: 'Wheaton',
    address: '965 Cooper Street, Ilchester, Wisconsin, 2248',
  },
  {
    id: 1,
    price: 1705.82,
    noi: 144.02,
    capRate: 0.69,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.LEASE,
    name: 'Malone Snyder',
    dealName: 'Outlook',
    address: '566 Fairview Place, Cannondale, New Jersey, 7365',
  },
  {
    id: 57,
    price: 3495.71,
    noi: 148.52,
    capRate: 0.55,
    image: 'https://picsum.photos/200',
    dealType: EstateDealType.DEVELOPMENT,
    name: 'Chris Yang',
    dealName: 'Iola',
    address: '282 Dahill Road, Kapowsin, New Mexico, 3878',
  },
];
